update version
eclipse/che-dependencies pull request #98
Opened 2018-02-19 16:50 UTC by riuvshin

update version

2018-02-20 06:07 UTC, tolusha approved these changes

2018-02-20 06:07 UTC, tolusha requested changes

2018-02-20 06:07 UTC, tolusha commented on pom.xml
> +        <version>6.2.0-SNAPSHOT</version>
Hold on, I will do it myself.

2018-02-20 06:42 UTC, skabashnyuk approved these changes

2018-06-23 07:30 UTC, skabashnyuk commented
out of date

2018-06-23 07:30 UTC, closed without merging